inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/*"
    - "Gemfile"
    - "Rakefile"
    - !ruby/regexp /old_and_unused\.rb$/

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/GlobalStdStream:
  Enabled: false
